name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: run shell script
        run: |
          bash ./run.sh

      - name: 部署到Cloudflare Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: cf-pages
          folder: public
